title: TechWorkshop Workforce Management
description: This lab walks you t.
theme: just-the-docs

aux_links:
  "TechWorkshop L400: Workforce Management": 
    - "https://github.com/microsoft/TWL400-Workforce-Management"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
